// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2X-ZnRsrVnPimn-dds7Y8p00TqklvqC0',
    appId: '1:977378904457:web:b9da1db889b3b1454c3958',
    messagingSenderId: '977378904457',
    projectId: 'travel-journal-app-edebe',
    authDomain: 'travel-journal-app-edebe.firebaseapp.com',
    storageBucket: 'travel-journal-app-edebe.firebasestorage.app',
    measurementId: 'G-79S7SXQPBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRZj2f8fzysgStHKKcFJdaRCVmIuwvgo0',
    appId: '1:977378904457:android:e949b3043b5849cd4c3958',
    messagingSenderId: '977378904457',
    projectId: 'travel-journal-app-edebe',
    storageBucket: 'travel-journal-app-edebe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsbJJOl0YZw14WZtiZOP8vu1eTq_RExCU',
    appId: '1:977378904457:ios:d48fed93e8fa5ec74c3958',
    messagingSenderId: '977378904457',
    projectId: 'travel-journal-app-edebe',
    storageBucket: 'travel-journal-app-edebe.firebasestorage.app',
    iosBundleId: 'com.example.travelJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsbJJOl0YZw14WZtiZOP8vu1eTq_RExCU',
    appId: '1:977378904457:ios:d48fed93e8fa5ec74c3958',
    messagingSenderId: '977378904457',
    projectId: 'travel-journal-app-edebe',
    storageBucket: 'travel-journal-app-edebe.firebasestorage.app',
    iosBundleId: 'com.example.travelJournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2X-ZnRsrVnPimn-dds7Y8p00TqklvqC0',
    appId: '1:977378904457:web:c379684f4122086d4c3958',
    messagingSenderId: '977378904457',
    projectId: 'travel-journal-app-edebe',
    authDomain: 'travel-journal-app-edebe.firebaseapp.com',
    storageBucket: 'travel-journal-app-edebe.firebasestorage.app',
    measurementId: 'G-9KQPZKLVCC',
  );
}
